name: Test de Infraestructura Tesis
on: [push]

jobs:
  check-casa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # ESTE ES EL PASO MÁGICO: Conecta la VM de GitHub a tu red privada
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_CLIENT_SECRET }}

      - name: Conectar a CachyOS y ejecutar Podman
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "--- ¡CONEXIÓN EXITOSA DESDE EL TÚNEL! ---"
            podman --version
